### ISSUE TITLE
background_callback error in fdroid-dl 0.0.1

### ISSUE THREAD

**Issue by clove3am** [t4skforce/fdroid-dl#3]
When running ```fdroid-dl -d update``` I get this error.

```
FuturesSessionFlex - WARNING - `background_callback` is deprecated and will be removed in 1.0, use `hooks` instead
```

**Full output:**
```bash
fdroid-dl -d update
2018-12-19 08:02:40,696 - fdroid-dl - INFO - Debug mode is on
2018-12-19 08:02:40,697 - FuturesSessionFlex - WARNING - `background_callback` is deprecated and will be removed in 1.0, use `hooks` instead
save
Traceback (most recent call last):
  File "/home/caltlgin/.local/bin/fdroid-dl", line 11, in <module>
    sys.exit(cli())
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/core.py", line 1114, in invoke
    return Command.invoke(self, ctx)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/fdroid_dl/__init__.py", line 58, in update
    u.index()
  File "/home/caltlgin/.local/lib/python3.6/site-packages/fdroid_dl/update/update.py", line 25, in index
    self.__index.download(*self.__index.required(self.__config.repos,timeout=self.__head_timeout),timeout=self.__index_timeout)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/fdroid_dl/update/index.py", line 22, in required
    head_futures = self.__future(repos=repos,timeout=timeout)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/fdroid_dl/update/index.py", line 55, in __future
    futures.append(request)
  File "/home/caltlgin/.local/lib/python3.6/site-packages/requests/sessions.py", line 424, in __exit__
    self.close()
  File "/home/caltlgin/.local/lib/python3.6/site-packages/fdroid_dl/download/futuressession.py", line 113, in close
    self.__default_sessions.close()
AttributeError: 'FuturesSessionFlex' object has no attribute '_FuturesSessionFlex__default_sessions'
```

**Comment by t4skforce** [comment]
Hi @caltlgin,

thanks for trying this little project of mine. I just merged a bugfix for this issue. But it had nothing to do with `background_callback` being deprecated ;). I anyways also fixed this up as it was a quick fix. I am currently under time restraints an haven't got the time to spend lot's of hours in this project so sorry for that in advance. I'll also bump the version and update the pypy package so 0.0.2 should be installable via pip in a jiffy. Tell me if it works for you, so we can close this issue.

**Comment by clove3am** [comment]
Hi @t4skforce. Thanks for the update.

I have updated to version 0.0.2 via pip and I no longer get the ```background_callback``` issue.

I am closing https://github.com/t4skforce/fdroid-dl/issues/3
