### ISSUE TITLE
Cannot import name 'NAME'

### ISSUE THREAD

**Issue by gspeiliu** [t4skforce/fdroid-dl#8]
ImportError: cannot import name 'NAME' from 'fdroid_dl'

How can I fix this issue?

Thanks,

**Comment by t4skforce** [comment]
can you maybe provide more debug information? is it installed vie pip, git clone? where do you get the error message? what is the full output?

**Comment by Glennmen** [comment]
I found this project today and it looks perfect from what I want to do but I am having the same issue.

Steps:
* `pip3 install fdroid-dl`
* `echo '{}' > ./fdroid-dl.json` (because I first assumed that the file not being available might give the error)
* `fdroid-dl -c ./fdroid-dl.json update --no-index --no-metadata --no-apk --no-src`

The error:
```
Traceback (most recent call last):
  File "/usr/local/bin/fdroid-dl", line 5, in <module>
    from fdroid_dl.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/fdroid_dl/__main__.py", line 7, in <module>
    from . import NAME
ImportError: cannot import name 'NAME' from 'fdroid_dl' (/usr/local/lib/python3.7/site-packages/fdroid_dl/__init__.py)
```

**Comment by Glennmen** [comment]
@t4skforce I *think* I found out why, this commit removed `NAME` from `__init.py__` https://github.com/t4skforce/fdroid-dl/commit/43093c627c34bd0bdd534b4e0412376d60ef0773#diff-9a77e494f2f317d16adf7ec9b7f42524
But my knowledge in Python is not that great to be sure 😅

**Comment by Glennmen** [comment]
When I downgrade to version `0.0.4` I am not having this error.

**Comment by t4skforce** [comment]
fixed in "0.1.0" please try again

**Comment by Glennmen** [comment]
This does fix this issue 👍 
But I am getting an other error when trying to import metadata (using the default config), it is throwing an error when trying to write `full_description.txt` but I might open an other issue for this.
